#+title: Mid



（1）论文课题的进展情况；

（2）存在问题和解决思路；

（3）下一步工作计划和研究报告。

我的项目概要：
数字认知是人类基本认知能力的重要组成部分，关乎我们的日常生活和基础学习。通过功能磁共振成像(fMRI)数据，探索人脑中数字和基本算术的表示，有助于揭示人脑处理和理解数字的机理，对教育、心理学、疾病治疗甚至人工智能的发展都有深远影响。

了解发展性计算障碍（Developmental Dyscalculia, DD）的神经生物学基础对于研究人脑对数字的认知具有重要意义。DD是一种数学学习障碍，表现为在基本数字处理、心算和视觉空间工作记忆等方面的困难。通过研究DD儿童与正常发育儿童之间的大脑功能差异，我们可以更深入地了解人脑对数字的认知和处理机制。

在这一研究中，我们使用了一份涵盖了68名儿童（8-10岁，其中30名为DD儿童）的功能磁共振成像（fMRI）数据。该数据旨在调查DD儿童常见行为缺陷相关的功能神经解剖学差异，包括基本数字处理、心算和视觉空间工作记忆（VSWM）。通过分析这些数据，我们可以更深入地了解人脑对数字的认知方式。


（1）论文课题的进展情况；
调研：我学习了MRI数据的BIDS规范与结构，如何使用软件工具处理MRI数据，以及MRI数据预处理操作和作用
探索数据集结构和采集情况：我使用pybids,openneuro,nilearn等工具初步探索了该数据集的结构和各个任务的采集情况细节，并用python venv, nix flake等工具构建了可复现的开发环境。在对数据的探索中，我尝试确定数据集的预处理程度，但是除了原文献中提及的de-face步骤之外，不能确定该数据集是否经过其他数据处理步骤。通过探索fMRI数据，我发现数据没有被归一化到MNI space。为了后续将不同受试者的神经反应一起比较分析，我尝试使用文章中提及的fMRIPrep流程进行数据预处理。



（2）存在问题和解决思路；
存在问题：
在成功开始使用fMRIPrep对数据进行预处理后，我意识到使用单个docker容器处理全体数据会使用大量CPU时间。哪怕是单个被试数据在Intel Core i7-13700处理器上使用8线程，开启低内存消耗模式的情况下，也需要十几小时甚至更多才能完成处理。况且fMRIPrep的流程也并非全都必要。所以需要考虑哪些预处理流程是必须进行的，以及寻找新的软件工具。

解决思路：
了解哪些预处理步骤对于这项研究是必要的；使用其他归一化工具把数据映射到MNI space；探索文章作者发布的数据集已经进行过哪些数据预处理步骤。

（3）下一步工作计划和研究报告。
首先完成数据集的数据处理，保证不同被试的神经相应被映射到同一空间。然后选定任务开始后与任务相关性最高的时间差，观察在item-matching task中被试的对不同数字类别是否存在不同的神经相应。
